### ISSUE TITLE
Pure JQL as events source

### ISSUE THREAD

**Issue by mashintsev** [mailru/jira-plugins-mailrucal#37]
Bugs:
- [x] ~~Use tooltip for project names~~
- [x] ~~Can we reuse styles from picker?~~
- [x] ~~Unavailable filter is displayed with project icon. Please test unavailable filter and project behaviour.~~
- [x] ~~1x1 pixel is shown instead of error description tooltip~~
- [x] ~~Syntax Help link is not clickable~~
- [x] ~~Found 11 issues link url is not updated sometimes~~
- [x] ~~Empty JQL is considered as valid initially, but as invalid after some changes~~
- [x] ~~Validation order should be the same as on the display~~
- [x] ~~Display several JQL checking errors separately~~
- [x] ~~Different error messages for Project, Filter or JQL required~~
- [x] ~~Wrap radios with Label~~
- [x] ~~Selected radio should be focused on tab panel opening~~
- [x] ~~For all unavailable calendars we have a tooltip with problem description. We have long tooltips for Unavailable filter and Unavailable calendar and a long one for Unavailable project. We should have the same type for all of them. I like short one much more.~~
- [x] ~~JQL Query field error is cleaned automatically after changing it. It is a wrong behaviour, cause it works differently for other fields~~

**Comment by andreymolchanov** [comment]
- [ ] Use tooltip for project names
- [ ] Can we reuse styles from picker? 
- [ ] Test "Unavailable project"
- [ ] Filter picker group name is not shown
- [ ] Filter picker shows me 585 of 591 filters when search for "f" letter - quite a strange optimization
- [ ] Test "Unavailable filter"
- [ ] Something is wrong with styles of select2 focus rendering
- [ ] 1x1 pixel is shown instead of error description tooltip
- [ ] Syntax Help link is not clickable
- [ ] Found 11 issues link url is not updated sometimes
- [ ] Empty JQL is considered as valid initially, but as invalid after some changes
