### ISSUE TITLE
Mail.Ru Calendar needs to display (iso) week numbers and allow to customise date format

### ISSUE THREAD

**Issue by mashintsev** [mailru/jira-plugins-mailrucal#44]
Currently there is no way to display week numbers with the Mail.Ru Calendar. I have implemented them myself but since the calendar is mostly a Javascript application, the implementation needs to use a MutationObserver to detect when the dates have been inserted into the calendar and this makes it unnecessarily difficult to do (i.e. it works but is by no means simple and most users will not be able to add them in). In our case we need ISO week numbers but this could be a configurable setting.
In addition to the week numbers, the date formatting should be configurable. I'd like to see month and not only the day (e.g. "14.4." instead of the default "14") for each date.
A documented way to provide custom CSS for the calendar would also come in handy. For example, in the Quarter view we display the first of of each month in a different background color.

**Comment by tomikall** [comment]
Here's a quick screenshot of some of the customisations we have implemented:

![screenshot 2016-04-14 12 02 45](https://cloud.githubusercontent.com/assets/132639/14522774/d8090268-0238-11e6-8733-5c67f3088413.png)

- week numbers on the left
- customised date format
- custom css for first-of-month

**Comment by andreymolchanov** [comment]
I think, we should do the following:
1. Add custom css class for the first day (undocumented for now)
2. Add week numbers on the left, but *only for Quarter mode*
3. Add month number for cells (only for Quarter mode and if there is such an internationalized option in fullcalendar)

**Comment by mashintsev** [comment]
Fullcalendar doesn't support dynamically enable/disable showing week numbers.

**Comment by tomikall** [comment]
I understand you are somewhat limited by the calendar component that you use but I would like to stress the fact that as a _user_ of your add-on, we don't really care about the internals of the implementation, we only care about what it can do for us (don't take this wrong; it already does a lot for us and you can't really beat the price).

Commentary for the points presented above:

1. Good, a documented css class is fine. Another nice way to distinguish months from each other is to display every other month in a slightly different (e.g. very light gray) background colour.

2. Why week numbers only for Quarter mode? They are equally useful information in the Month mode, and usable also in the Week mode. This depends on the locale of course as some locales use week numbers a lot while others never refer to them. We tend to use week numbers a lot when scheduling things so they are important to us, no matter which view is visible.

3. I wouldn't add month numbers to cells as different usage scenarios for the calendar add-on might require different types of date formatting. Again, depending on the locale some might wish to see "2.4." (the format we tend to use) or "April 2". I don't think you can guess the right format for the user but this should be a configurable setting.

These could be difficult to implement due to the underlaying calendar component. I want to express my gratitude for you guys because you try. So thanks!

**Comment by mashintsev** [comment]
Check out 2.4 version.

1) This class  is 'fc-first-day-of-month'. How do you want distinguish months? 'fc-june', 'fc-july' or 'fc-current', 'fc-past-month', 'fc-next-month'? 
2) We stay week numbers for all views.
3) We will think about configuration options for users.

**Comment by tomikall** [comment]
1) For my purposes, I think "fc-odd" and "fc-even" would be enough. That way I can "stripe" the months. Having "fc-current" is beneficial too so that the current month can be highlighted when needed.
2) Week numbers seem to be working fine, thanks! They are ISO week numbers (which we use) but I wonder what people on other locales will see as week numbers are not standard throughout the world. Should the calendar be able to display week numbers according to a given locale; i.e. different locale that the user currently has (e.g. when the team has to use a specific numbering scheme while team members' browsers can have whatever settings the users prefer).
3) Thank you for time and efforts!
